### ISSUE TITLE
Checkpoint and Minimum Runnable Notebook

### ISSUE THREAD

**Issue by ratthachat** [JDAI-CV/image-captioning#1]
Hi, Great job!

It would be great if you can provide model checkpoints and notebook which show the results of the paper.

**Comment by Panda-Peter** [comment]
Thanks for your suggestion. Till now, we have released all the final models and results in https://drive.google.com/file/d/1a7aINHtpQbIw5JbAc4yvC7I1V-tQSdzb/view?usp=drive_open . Details of results can be referred in our paper (https://arxiv.org/pdf/2003.14080.pdf).
