### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by akonstantinou** [JDAI-CV/image-captioning#11]
What GPU did you use for training? I try to train on a 2080 TI with 11 GB of RAM with the configuration file from transformer_rl and i get the following error

RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 10.76 GiB total capacity; 9.83 GiB already allocated; 9.56 MiB free; 72.86 MiB cached)

**Comment by YehLi** [comment]
We use Tesla P40 (22 GB).
