### ISSUE TITLE
Problems about the provided annotations file

### ISSUE THREAD

**Issue by jlxy** [JDAI-CV/image-captioning#15]
Hello, thanks for this good work.
I think I downloaded and placed the annotations file right, because I can read the captions and image_ids out of the data.
The problem I met is a _KeyError_ in coco-caption/pycocotools/coco.py, when running _if self.dataset['type'] == 'instances':_. This suggests that the dict self.data read from ./mscoco/misc/captions_val5k.json, should has the key "type", but it doesn't.
Please help!

**Comment by jlxy** [comment]
Could you please provide the code that produce the annotations files?

**Comment by YehLi** [comment]
You can remove the "if self.dataset['type'] == 'instances'" block in coco.py. The annotation of segmentation is not used for image captioning.
