### ISSUE TITLE
Why you didn't apply scheduled sampling when training the xtransformer model？

### ISSUE THREAD

**Issue by jlxy** [JDAI-CV/image-captioning#16]
Hello.
I notice that you didn't apply scheduled sampling when training the xtransformer model. 
Could you tell me the reason? 
Thanks.

**Comment by YehLi** [comment]
Unlike RNN-based models, transformer is trained in parallel for all words. Therefore, scheduled sampling can't be applied to transformer directly. For more details, you can refer to the paper "Scheduled Sampling for Transformers".
