### ISSUE TITLE
Missing file /mscoco/feature/up_down_100/391895.npz. Where can  I find it?

### ISSUE THREAD

**Issue by HungPhan1995** [JDAI-CV/image-captioning#22]

**Comment by YehLi** [comment]
Please download the tsv files from https://github.com/peteanderson80/bottom-up-attention and convert them into npz format by tools/create_feats.py

**Comment by yrr12** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/user1/imagecaption/code/image-captioning-master/mscoco/feature/up_down_100/104368.npz'
