### ISSUE TITLE
Test results are all 0 when using the author's checkpoint

### ISSUE THREAD

**Issue by XuMengyaAmy** [JDAI-CV/image-captioning#23]
1) I used the provided caption_model_47.pth from xlan experiment and the following commands to do the test. However,
**all test metrics are 0 when I used the def decode_beam which is inspired by meshed-memory-transformer.**
https://github.com/JDAI-CV/image-captioning/blob/master/models/att_basic_model.py
https://github.com/JDAI-CV/image-captioning/blob/master/models/xtransformer.py

And it's the same case for the xlan+transformer test. **I feel the decode_beam (from m2transformer) has problems.**
Do you have the same issue? Can you help to solve it? Thanks.

What I changed in the  decode_beam(self, **kwargs)  is adding .long() after some variable because of the error issue. 
**2) What's inside coco_train_cider.pkl? How to generate this file for custom dataset?**
3) And I noticed that you used input_seq and target seq. From my understanding, both of them are ground truth caption which represented by word index, correct? The only difference is 0 and -1 at the end. Can you provide the preprocess code which convert the ground truth caption to word index?

Test Results:
python3.8 main_test.py --folder experiments/xlan --resume 47
Called with args:
Namespace(folder='experiments/xlan', resume=47)
/media/mmlab/data_2/mengya/Code/ImageCaption/image-captioning/lib/config.py:381: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
139it [00:11, 12.16it/s]
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
tokenization...
PTBTokenizer tokenized 307085 tokens at 1576551.76 tokens per second.
PTBTokenizer tokenized 4999 tokens at 130967.27 tokens per second.
setting up scorers...
computing Bleu score...
{'testlen': 0, 'reflen': 42485, 'guess': [0, 0, 0, 0], 'correct': [0, 0, 0, 0]}
ratio: 2.3537719195009454e-20
Bleu_1: 0.000
Bleu_2: 0.000
Bleu_3: 0.000
Bleu_4: 0.000
computing METEOR score...
METEOR: 0.000
computing Rouge score...
ROUGE_L: 0.000
computing CIDEr score...
CIDEr: 0.000
computing SPICE score...
Parsing reference captions
Parsing test captions
SPICE evaluation took: 3.045 s
SPICE: 0.000

**Comment by YehLi** [comment]
1. Please try to change "selected_beam = selected_idx / candidate_logprob.shape[-1]" to "selected_beam = selected_idx // candidate_logprob.shape[-1]" for new pytorch version. The code can work correctly in my server after this change (torch version 1.8.1).

2. tools/cider_cache.py is the code for coco_train_cider.pkl

3. The code for input_seq and target seq:

for cocoid in annos:
     n = len(annos[cocoid]['final_captions'])
     input_seq = np.zeros((n, args.max_length + 1), dtype='uint32')
     target_seq = np.zeros((n, args.max_length + 1), dtype='int32') - 1
     for j,s in enumerate(annos[cocoid]['final_captions']):
           for k,w in enumerate(s):
               if k < args.max_length:
                    input_seq[j,k+1] = wtoi[w]
                    target_seq[j,k] = wtoi[w]
           seq_len = len(s)
           if seq_len <= args.max_length:
                target_seq[j,seq_len] = 0
            else:
                target_seq[j,args.max_length] = wtoi[s[args.max_length]]

**Comment by alice-cool** [comment]
> 1. I used the provided caption_model_47.pth from xlan experiment and the following commands to do the test. However,
>    **all test metrics are 0 when I used the def decode_beam which is inspired by meshed-memory-transformer.**
>    https://github.com/JDAI-CV/image-captioning/blob/master/models/att_basic_model.py
>    https://github.com/JDAI-CV/image-captioning/blob/master/models/xtransformer.py
> 
> And it's the same case for the xlan+transformer test. **I feel the decode_beam (from m2transformer) has problems.**
> Do you have the same issue? Can you help to solve it? Thanks.
> 
> What I changed in the decode_beam(self, **kwargs) is adding .long() after some variable because of the error issue.
> **2) What's inside coco_train_cider.pkl? How to generate this file for custom dataset?**
> 3) And I noticed that you used input_seq and target seq. From my understanding, both of them are ground truth caption which represented by word index, correct? The only difference is 0 and -1 at the end. Can you provide the preprocess code which convert the ground truth caption to word index?
> 
> Test Results:
> python3.8 main_test.py --folder experiments/xlan --resume 47
> Called with args:
> Namespace(folder='experiments/xlan', resume=47)
> /media/mmlab/data_2/mengya/Code/ImageCaption/image-captioning/lib/config.py:381: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> yaml_cfg = edict(yaml.load(f))
> loading annotations into memory...
> Done (t=0.03s)
> creating index...
> index created!
> 139it [00:11, 12.16it/s]
> Loading and preparing results...
> DONE (t=0.01s)
> creating index...
> index created!
> tokenization...
> PTBTokenizer tokenized 307085 tokens at 1576551.76 tokens per second.
> PTBTokenizer tokenized 4999 tokens at 130967.27 tokens per second.
> setting up scorers...
> computing Bleu score...
> {'testlen': 0, 'reflen': 42485, 'guess': [0, 0, 0, 0], 'correct': [0, 0, 0, 0]}
> ratio: 2.3537719195009454e-20
> Bleu_1: 0.000
> Bleu_2: 0.000
> Bleu_3: 0.000
> Bleu_4: 0.000
> computing METEOR score...
> METEOR: 0.000
> computing Rouge score...
> ROUGE_L: 0.000
> computing CIDEr score...
> CIDEr: 0.000
> computing SPICE score...
> Parsing reference captions
> Parsing test captions
> SPICE evaluation took: 3.045 s
> SPICE: 0.000

How do you deal with the following bug?
![image](https://user-images.githubusercontent.com/16870890/124604174-455ebb00-de9d-11eb-80a9-939b08fc00c0.png)

![image](https://user-images.githubusercontent.com/16870890/124604390-7808b380-de9d-11eb-8f4c-a826e253fc57.png)
Please help me

**Comment by alice-cool** [comment]
> 1. Please try to change "selected_beam = selected_idx / candidate_logprob.shape[-1]" to "selected_beam = selected_idx // candidate_logprob.shape[-1]" for new pytorch version. The code can work correctly in my server after this change (torch version 1.8.1).
> 2. tools/cider_cache.py is the code for coco_train_cider.pkl
> 3. tools/create_labels.py is the code for input_seq and target seq

How to fix the error? Did you see it? When using create_feats.py to produce many npy file. But Every time when running 10000, it will throw the exception.
![image](https://user-images.githubusercontent.com/16870890/124683618-031a9580-df00-11eb-91de-15a90852b5c9.png)

**Comment by alice-cool** [comment]
> 1. Please try to change "selected_beam = selected_idx / candidate_logprob.shape[-1]" to "selected_beam = selected_idx // candidate_logprob.shape[-1]" for new pytorch version. The code can work correctly in my server after this change (torch version 1.8.1).
> 2. tools/cider_cache.py is the code for coco_train_cider.pkl
> 3. tools/create_labels.py is the code for input_seq and target seq

I also use python2 with usual way ,for example. padding "=" to making it but it also didn't work.

**Comment by shamimsareem** [comment]
Transformer main_test result all are zero , please help:    [INFO: 2024-03-16 19:09:05,645] {'Bleu_1': 0.0, 'Bleu_2': 0.0, 'Bleu_3': 0.0, 'Bleu_4': 0.0, 'METEOR': 0.0, 'ROUGE_L': 0.0, 'C
