### ISSUE TITLE
How to generate the visualization of attended image regions along the caption generation processes.

### ISSUE THREAD

**Issue by Archer-Fang** [JDAI-CV/image-captioning#26]
I have a question for how to generate the visualization of attended image regions along the caption generation processes. Would you mind releasing some codes?

**Comment by cdqncn** [comment]
no way

**Comment by Baixiaobai201619707** [comment]
> I have a question for how to generate the visualization of attended image regions along the caption generation processes. Would you mind releasing some codes?
请问您知道怎么做了吗，可以告知一下吗？ 谢谢！

**Comment by YehLi** [comment]
You can save the attention score into a txt file and then use the link (https://github.com/peteanderson80/Up-Down-Captioner/blob/master/scripts/demo.ipynb) to generate the visualization
