### ISSUE TITLE
Ensemble code and how to use senet154 

### ISSUE THREAD

**Issue by searchstorm** [JDAI-CV/image-captioning#29]
你好，请问可以提供ensemble的代码吗，还有论文说的以senet154为backbone是指将faster rcnn的backbone换成了senet 还是直接用它提取特征？有提取好的特征数据吗？

**Comment by YehLi** [comment]
The senet154 features have been released(Data preparation -- The pretrained SENet-154 model can be downloaded [here](https://drive.google.com/file/d/1CrWJcdKLPmFYVdVNcQLviwKGtAREjarR/view?usp=sharing))

You can refer to the code for ensemble (https://github.com/YehLi/xmodaler/blob/master/xmodaler/modeling/decode_strategy/ensemble_beam_searcher.py)
