### ISSUE TITLE
Reg. Training time

### ISSUE THREAD

**Issue by deepak242424** [JDAI-CV/image-captioning#4]
Hi,

Thanks for sharing your code here.

Can you please tell on what type of GPUs you training your model, how much time it took to complete one epoch and the number of epochs till you run your model?

Regards
Deepak Mittal

**Comment by Jordan-5i** [comment]
I run the code on Tesla, 4GPUs, it takes me about 30 min for one epoch with XE.`bash experiments/xlan/train.sh`

**Comment by Jordan-5i** [comment]
@deepak242424

**Comment by Panda-Peter** [comment]
Take xtransformer as an example, 20-30 min for one epoch on 4GPUs (P40) with cross-entropy optimization. The best results are obtained around 30~50 epoches. For RL optimization, it takes ~2.5 hours for one epoch on 1GPU. The best results are obtained around 50 epoches.
