### ISSUE TITLE
About Ensemble/Fusion model in paper

### ISSUE THREAD

**Issue by Jordan-5i** [JDAI-CV/image-captioning#5]
我最近阅读了你的论文，我对Ensemble/Fusion model 有疑惑。这个Ensemble/Fusion model是用的哪些模型，是不是X-Linear和Xtransformer一起去生成caption的吗？可以具体说一下吗？

**Comment by Panda-Peter** [comment]
X-Linear和Xtransformer是各自ensemble的。对于每个方法，只是改了random seed，然后fusion。

**Comment by Jordan-5i** [comment]
也就是X-Linear的fusion或者Xtransformer的fusion，是不是他们的模型结构都是完全相同的，只是模型之间的参数值不一样而已？

**Comment by Panda-Peter** [comment]
训练参数都是一样的，只是random seed不一样。

**Comment by Jordan-5i** [comment]
顺便问一下，你是几个模型做fusion

**Comment by Panda-Peter** [comment]
四个。

**Comment by ShiZiqiang** [comment]
Amazing work! I wander how to do the ensemble? Before the final softmax or after softmax? Is the ensemble just the average of output embedding matrix? Sorry for this stupid question.

**Comment by Panda-Peter** [comment]
The ensemble is performed by fusing the predicted scores after softmax.

**Comment by ShiZiqiang** [comment]
Thank you so much.

**Comment by WangLanxiao** [comment]
> The ensemble is performed by fusing the predicted scores after softmax.

Thanks for you contribution!
Does this ensemble method like the beamsearch？ Just beamsearch happens in the same model, the ensemble method makes beamsearch in more models?
