### ISSUE TITLE
X-transformer model batch_size setting

### ISSUE THREAD

**Issue by yaopengzero** [JDAI-CV/image-captioning#7]
Hello, did you train all the model using one GPU once? if so, when training the X-transformer model, the default batch_size setting is 40 and it will out of memory(1080TI 12G), but if we set it 10, the cider score will lower than you.

**Comment by Panda-Peter** [comment]
Thanks for your interest in our work. We directly run our experiments on 4GPUs (P40), and did not try the training on only one GPU.

**Comment by sorrowyn** [comment]
> 

1080TI 12GB ????
